# Generated by Django 5.0.4 on 2024-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVDAddition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specs', models.CharField(choices=[('700 MB', '700 MB'), ('4.4 GB', '4.4 GB'), ('08 GB', '08 GB'), ('25 GB', '25 GB')], max_length=10)),
                ('classification', models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD'), ('BLUE RAY', 'BLUE RAY')], max_length=10)),
                ('purchase_date', models.DateTimeField()),
                ('purchased_by', models.CharField(choices=[('P&QM', 'P&QM'), ('SI', 'SI'), ('ANYOTHER', 'ANYOTHER')], max_length=10)),
                ('booking_status', models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], default='Available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
