# Generated by Django 5.0.4 on 2024-05-01 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_dvdmgmt', '0003_alter_dvdaddition_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReceiveRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issued_to', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_by', models.CharField(max_length=100)),
                ('returned_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('WORKING', 'WORKING'), ('OUT OF ORDER', 'OUT OF ORDER'), ('ANYOTHER', 'ANYOTHER')], max_length=20)),
                ('purpose', models.CharField(choices=[('CIF', 'CIF'), ('Upload/ Download (e-Office)', 'Upload/ Download (e-Office)'), ('Media', 'Media')], max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('return_status', models.CharField(choices=[('RETURNABLE', 'RETURNABLE'), ('NON-RETURNABLE', 'NON-RETURNABLE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'issue_receive_record',
                'managed': False,
            },
        ),
    ]
